name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures git history is available

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          ftp-server: "ftp.gurjargaudindia.com"
          ftp-username: "ftpGit@new.gurjargaudindia.com"
          ftp-password: "*w-chqyyH{2i"
