name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures git history is available

      - name: FTP Deploy
        uses: Sachin-Eway/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: 'ftp.gurjargaudindia.com'
          ftp-username: 'ftp_git_connect@new.gurjargaudindia.com'
          ftp-password: 'QGPHU5yZ6(yt'
          git-ftp-args: "--insecure --force --verbose --remote-root /public_html/new-site"
