name: SSH Deploy & Composer Install

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH Deploy & Run Composer
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "gurjargaudindia.com"
          username: "indiagurjargaud"
          password: "Iks0OzcR9#mQ"
          port: 22
          script: |
            cd public_html/new.gurjargaudindia.com/ftpGit
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
