name: Auto Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "gurjargaudindia.com"
          username: "indiagurjargaud"
          password: "Iks0OzcR9#mQ"
          port: 22
          script: |
            echo "✅ SSH connection successful!"
            whoami
            hostname
            pwd
            ls -la
